import { StyleSheet } from 'react-native';
import { COLORS } from './constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.bg,
    },
    hero: {
        position: 'relative',
        height: 320,
    },
    heroImage: {
        width: '100%',
        height: '100%',
    },
    heroOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.18)',
    },
    heroActions: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    glassBtn: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: 'rgba(0,0,0,0.4)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    glassBtnFav: {
        backgroundColor: 'rgba(255,255,255,0.3)',
    },
    infoPanel: {
        backgroundColor: COLORS.surface,
        marginTop: -20,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 4,
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: -4 },
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginBottom: 8,
    },
    locationIcon: {
        fontSize: 14,
    },
    locationText: {
        fontSize: 14,
        color: COLORS.textMuted,
        fontWeight: '600',
    },
    titlePriceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 12,
        marginBottom: 12,
    },
    tourTitle: {
        flex: 1,
        fontSize: 22,
        fontWeight: '800',
        color: COLORS.text,
        letterSpacing: 0,
        lineHeight: 30,
    },
    priceBlock: {
        alignItems: 'flex-end',
        flexShrink: 0,
    },
    priceLabel: {
        fontSize: 11,
        color: COLORS.textMuted,
        marginBottom: 2,
    },
    priceValue: {
        fontSize: 18,
        fontWeight: '800',
        color: COLORS.primary,
        lineHeight: 22,
    },
    pricePerPerson: {
        fontSize: 11,
        color: COLORS.textMuted,
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 4,
        flexWrap: 'wrap',
    },
    ratingPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#ffdcbf',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    ratingPillText: {
        fontSize: 13,
        fontWeight: '700',
        color: COLORS.tertiary,
    },
    ratingPillCount: {
        fontSize: 11,
        color: COLORS.tertiary,
        fontWeight: '500',
    },
    categoryTag: {
        backgroundColor: COLORS.primaryLight,
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    categoryTagText: {
        fontSize: 12,
        fontWeight: '700',
        color: COLORS.primary,
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: COLORS.surface,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border + '50',
        marginTop: 0,
    },
    tab: {
        flex: 1,
        paddingVertical: 14,
        alignItems: 'center',
    },
    tabActive: {
        borderBottomWidth: 2.5,
        borderBottomColor: COLORS.primary,
    },
    tabLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.textMuted,
    },
    tabLabelActive: {
        color: COLORS.primary,
        fontWeight: '700',
    },
    bentoGrid: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 14,
    },
    bentoCard: {
        flex: 1,
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        padding: 14,
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
    },
    bentoEmoji: {
        fontSize: 24,
        marginBottom: 6,
    },
    bentoLabel: {
        fontSize: 11,
        color: COLORS.textMuted,
        marginBottom: 4,
        fontWeight: '500',
    },
    bentoValue: {
        fontSize: 13,
        fontWeight: '800',
        color: COLORS.text,
        textAlign: 'center',
    },
    infoCard: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
    },
    infoCardTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: COLORS.text,
        marginBottom: 12,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
    },
    infoRowLabel: {
        fontSize: 14,
        color: COLORS.textMuted,
        fontWeight: '500',
    },
    infoRowValue: {
        fontSize: 14,
        fontWeight: '700',
        color: COLORS.text,
    },
    infoDivider: {
        height: 1,
        backgroundColor: COLORS.border + '40',
    },
    descText: {
        fontSize: 14,
        color: COLORS.textMuted,
        lineHeight: 22,
    },
    infoCardText: {
        fontSize: 14,
        color: COLORS.textMuted,
        lineHeight: 22,
        marginBottom: 2,
    },
    dayBlock: {
        marginBottom: 20,
    },
    dayHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 12,
    },
    dayDot: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: COLORS.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dayDotText: {
        fontSize: 13,
        fontWeight: '800',
        color: '#fff',
    },
    dayTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.primary,
    },
    dayActivities: {
        marginLeft: 40,
        gap: 10,
    },
    activityCard: {
        backgroundColor: COLORS.surface,
        borderRadius: 12,
        padding: 12,
        borderLeftWidth: 3,
        borderLeftColor: COLORS.primary,
        elevation: 1,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 6,
    },
    activityImage: {
        width: '100%',
        height: 140,
        borderRadius: 10,
        marginBottom: 10,
    },
    actTime: {
        fontSize: 11,
        color: COLORS.textMuted,
        marginBottom: 4,
        fontWeight: '500',
    },
    actTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: COLORS.text,
        marginBottom: 4,
    },
    actDesc: {
        fontSize: 13,
        color: COLORS.textMuted,
        marginBottom: 4,
        lineHeight: 18,
    },
    actLocation: {
        fontSize: 12,
        color: COLORS.success,
        fontWeight: '600',
    },
    reviewForm: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
    },
    reviewFormTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: COLORS.text,
        marginBottom: 12,
    },
    starRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginBottom: 12,
    },
    starBtn: {
        padding: 4,
    },
    starText: {
        fontSize: 28,
    },
    ratingNum: {
        marginLeft: 8,
        fontSize: 14,
        color: COLORS.textMuted,
        fontWeight: '600',
    },
    reviewInput: {
        borderWidth: 1.5,
        borderColor: COLORS.border,
        borderRadius: 12,
        padding: 12,
        fontSize: 14,
        color: COLORS.text,
        minHeight: 90,
        textAlignVertical: 'top',
        marginBottom: 12,
        lineHeight: 20,
    },
    submitBtn: {
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        padding: 14,
        alignItems: 'center',
        elevation: 3,
        shadowColor: COLORS.primary,
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    submitBtnText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 14,
    },
    reviewsCount: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.text,
        marginBottom: 10,
    },
    reviewCard: {
        backgroundColor: COLORS.surface,
        borderRadius: 14,
        padding: 14,
        marginBottom: 10,
        elevation: 1,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 6,
    },
    reviewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 10,
    },
    reviewAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: COLORS.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    reviewUser: {
        fontSize: 14,
        fontWeight: '700',
        color: COLORS.text,
    },
    reviewStars: {
        flexDirection: 'row',
        gap: 2,
        marginTop: 2,
    },
    reviewDate: {
        fontSize: 12,
        color: COLORS.textMuted,
        marginLeft: 'auto',
    },
    reviewComment: {
        fontSize: 14,
        color: COLORS.textMuted,
        lineHeight: 20,
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 30,
    },
    emptyText: {
        fontSize: 15,
        color: COLORS.textMuted,
        marginTop: 8,
        fontWeight: '500',
    },
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        backgroundColor: COLORS.surface + 'F0',
        paddingHorizontal: 16,
        paddingVertical: 14,
        paddingBottom: 26,
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: COLORS.border + '40',
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: -4 },
    },
    favBtnBottom: {
        width: 54,
        height: 54,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.surface,
    },
    favBtnBottomActive: {
        borderColor: '#ef4444',
        backgroundColor: '#fff0f0',
    },
    bookBtn: {
        flex: 1,
        backgroundColor: COLORS.primary,
        borderRadius: 16,
        height: 54,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
        elevation: 4,
        shadowColor: COLORS.primary,
        shadowOpacity: 0.35,
        shadowRadius: 10,
    },
    bookBtnText: {
        color: '#fff',
        fontWeight: '800',
        fontSize: 16,
    },
    bookBtnIcon: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
    },
});
