import { StyleSheet } from 'react-native';
import { COLORS } from './constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.bg,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingRight: 64,
        paddingVertical: 14,
        backgroundColor: COLORS.surface,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border + '40',
        position: 'relative',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatarCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.primaryDark,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: {
        fontSize: 16,
        fontWeight: '800',
        color: '#fff',
    },
    greetText: {
        fontSize: 12,
        color: COLORS.textMuted,
        fontWeight: '600',
    },
    userName: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.text,
    },
    notifBtn: {
        position: 'absolute',
        top: 8,
        right: 12,
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: COLORS.surfaceMuted,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    notifText: {
        fontSize: 18,
    },
    unreadBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        minWidth: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: COLORS.error,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
        borderWidth: 2,
        borderColor: COLORS.surface,
    },
    unreadBadgeText: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: '900',
    },
    overviewSection: {
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 14,
        backgroundColor: COLORS.bg,
    },
    introCard: {
        minHeight: 210,
        borderRadius: 18,
        overflow: 'hidden',
        marginBottom: 12,
        backgroundColor: COLORS.primary,
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
    },
    introImage: {
        borderRadius: 18,
    },
    introOverlay: {
        flex: 1,
        justifyContent: 'space-between',
        padding: 18,
        backgroundColor: 'rgba(7, 26, 35, 0.42)',
    },
    introBadge: {
        alignSelf: 'flex-start',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: 'rgba(255,255,255,0.88)',
    },
    introBadgeText: {
        color: COLORS.primaryDark,
        fontSize: 11,
        fontWeight: '900',
        textTransform: 'uppercase',
    },
    dashboardIntro: {
        maxWidth: '92%',
    },
    heroTitle: {
        color: '#ffffff',
        fontSize: 25,
        lineHeight: 31,
        fontWeight: '900',
        marginBottom: 8,
        textShadowColor: 'rgba(0,0,0,0.25)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 4,
    },
    heroSubtitle: {
        color: '#f8fafc',
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '700',
        textShadowColor: 'rgba(0,0,0,0.22)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    searchContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: COLORS.surface,
        gap: 8,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: COLORS.border + '55',
    },
    searchBox: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.surfaceMuted,
        borderRadius: 12,
        paddingHorizontal: 14,
        height: 46,
        gap: 8,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    searchIcon: {
        fontSize: 20,
        color: COLORS.textMuted,
        lineHeight: 22,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: COLORS.text,
        fontWeight: '600',
    },
    searchBtn: {
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 46,
        justifyContent: 'center',
    },
    searchBtnText: {
        color: '#fff',
        fontWeight: '800',
        fontSize: 14,
    },
    categoryScroll: {
        flexGrow: 0,
        paddingVertical: 12,
        backgroundColor: COLORS.surface,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border + '50',
    },
    categoryChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 13,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: COLORS.surfaceMuted,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    categoryChipActive: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
    },
    categoryText: {
        fontSize: 13,
        color: COLORS.textMuted,
        fontWeight: '700',
    },
    categoryTextActive: {
        color: '#fff',
    },
    section: {
        marginTop: 12,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        paddingHorizontal: 20,
        paddingVertical: 12,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: COLORS.text,
    },
    sectionSubtitle: {
        fontSize: 13,
        marginTop: 2,
        fontWeight: '600',
    },
    sectionCount: {
        fontSize: 13,
        color: COLORS.textMuted,
        fontWeight: '800',
    },
    tourCard: {
        flexDirection: 'row',
        backgroundColor: COLORS.surface,
        borderRadius: 14,
        marginBottom: 12,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
        borderWidth: 1,
        borderColor: COLORS.border + '80',
    },
    tourImage: {
        width: 116,
        minHeight: 148,
    },
    tourContent: {
        flex: 1,
        padding: 12,
    },
    cardTopRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        marginBottom: 6,
    },
    tourTitle: {
        flex: 1,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: '800',
        color: COLORS.text,
    },
    ratingBadge: {
        minWidth: 38,
        alignItems: 'center',
        backgroundColor: COLORS.warningLight,
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    ratingText: {
        fontSize: 12,
        fontWeight: '900',
        color: COLORS.warning,
    },
    locationText: {
        fontSize: 13,
        color: COLORS.textMuted,
        fontWeight: '700',
        marginBottom: 10,
    },
    tourMetaGrid: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    metaPill: {
        flex: 1,
        backgroundColor: COLORS.surfaceMuted,
        borderRadius: 999,
        paddingHorizontal: 9,
        paddingVertical: 5,
        fontSize: 12,
        color: COLORS.textMuted,
        fontWeight: '800',
    },
    slotsBadge: {
        backgroundColor: COLORS.primaryLight,
        borderRadius: 999,
        paddingHorizontal: 9,
        paddingVertical: 5,
    },
    slotsText: {
        fontSize: 12,
        color: COLORS.success,
        fontWeight: '800',
    },
    priceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    priceLabel: {
        fontSize: 11,
        color: COLORS.textMuted,
        marginBottom: 1,
        fontWeight: '700',
    },
    priceText: {
        fontSize: 17,
        fontWeight: '900',
        color: COLORS.accent,
    },
    detailBtn: {
        backgroundColor: COLORS.accentLight,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    detailBtnText: {
        color: COLORS.accent,
        fontWeight: '800',
        fontSize: 13,
    },
    emptyContainer: {
        alignItems: 'center',
        marginHorizontal: 20,
        paddingVertical: 46,
        paddingHorizontal: 18,
        borderRadius: 14,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    emptyTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: COLORS.text,
        marginTop: 12,
    },
    emptySubtitle: {
        fontSize: 13,
        color: COLORS.textMuted,
        marginTop: 4,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(17, 24, 39, 0.42)',
        justifyContent: 'flex-end',
    },
    notificationSheet: {
        maxHeight: '78%',
        backgroundColor: COLORS.surface,
        borderTopLeftRadius: 22,
        borderTopRightRadius: 22,
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 28,
    },
    notificationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 14,
        marginBottom: 16,
    },
    notificationHeaderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    notificationTitle: {
        fontSize: 22,
        fontWeight: '900',
        color: COLORS.text,
    },
    notificationSubtitle: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.textMuted,
        marginTop: 2,
    },
    closeBtn: {
        height: 38,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: COLORS.surfaceMuted,
        borderWidth: 1,
        borderColor: COLORS.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    closeBtnText: {
        color: COLORS.textMuted,
        fontSize: 13,
        fontWeight: '800',
    },
    readAllBtn: {
        height: 38,
        paddingHorizontal: 12,
        borderRadius: 10,
        backgroundColor: COLORS.primaryLight,
        borderWidth: 1,
        borderColor: COLORS.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    readAllBtnText: {
        color: COLORS.primaryDark,
        fontSize: 13,
        fontWeight: '900',
    },
    notificationEmpty: {
        alignItems: 'center',
        paddingVertical: 42,
        paddingHorizontal: 20,
    },
    notificationEmptyTitle: {
        fontSize: 16,
        fontWeight: '900',
        color: COLORS.text,
        marginBottom: 6,
    },
    notificationEmptyText: {
        fontSize: 13,
        color: COLORS.textMuted,
        textAlign: 'center',
        lineHeight: 19,
        fontWeight: '600',
        marginTop: 6,
    },
    retryNotificationBtn: {
        marginTop: 16,
        height: 40,
        paddingHorizontal: 18,
        borderRadius: 10,
        backgroundColor: COLORS.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    retryNotificationText: {
        color: '#ffffff',
        fontSize: 13,
        fontWeight: '900',
    },
    notificationItem: {
        flexDirection: 'row',
        gap: 12,
        padding: 14,
        borderRadius: 14,
        backgroundColor: COLORS.surfaceMuted,
        borderWidth: 1,
        borderColor: COLORS.border + '70',
        marginBottom: 10,
    },
    notificationItemUnread: {
        backgroundColor: COLORS.primaryLight,
        borderColor: COLORS.primary,
    },
    notificationIcon: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: COLORS.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    notificationIconDanger: {
        backgroundColor: COLORS.error,
    },
    notificationIconSuccess: {
        backgroundColor: COLORS.success,
    },
    notificationIconPayment: {
        backgroundColor: COLORS.accent,
    },
    notificationIconTour: {
        backgroundColor: COLORS.warning,
    },
    notificationIconText: {
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '900',
    },
    notificationItemTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        marginBottom: 4,
    },
    notificationItemTitle: {
        flex: 1,
        color: COLORS.text,
        fontSize: 14,
        fontWeight: '900',
    },
    notificationTime: {
        color: COLORS.textSoft,
        fontSize: 11,
        fontWeight: '700',
    },
    notificationMessage: {
        color: COLORS.textMuted,
        fontSize: 13,
        lineHeight: 19,
        fontWeight: '600',
    },
    notificationLink: {
        color: COLORS.accent,
        fontSize: 12,
        fontWeight: '900',
        marginTop: 8,
    },
});
